[workspace]
resolver = "2"

members = [
  "limiinal_client",
  "limiinal_relay",
]

[workspace.dependencies]
futures = "0.3.21"
tokio = { version = "1.41.1", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = "0.3"
libp2p = { version = "0.54.1" }
